version: '3.8'

services:
  bot:
    build: .
    container_name: rename_bot
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    network_mode: "host"
    restart: unless-stopped
